# Generated by Django 4.2.9 on 2024-03-18 11:03

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_aboutpage_banner_image_contactpage_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "agenda_layout",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "session",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("time", wagtail.blocks.CharBlock()),
                                                (
                                                    "session_title",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                                (
                                                    "language",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                                (
                                                    "program",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "timeline",
                                                                    wagtail.blocks.ListBlock(
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "time",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        required=False
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "title",
                                                                                    wagtail.blocks.RichTextBlock(),
                                                                                ),
                                                                                (
                                                                                    "description",
                                                                                    wagtail.blocks.RichTextBlock(
                                                                                        required=False
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "speakers",
                                                                                    wagtail.blocks.ListBlock(
                                                                                        wagtail.blocks.StructBlock(
                                                                                            [
                                                                                                (
                                                                                                    "name",
                                                                                                    wagtail.blocks.CharBlock(
                                                                                                        required=False
                                                                                                    ),
                                                                                                ),
                                                                                                (
                                                                                                    "designation",
                                                                                                    wagtail.blocks.CharBlock(
                                                                                                        required=False
                                                                                                    ),
                                                                                                ),
                                                                                            ]
                                                                                        )
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        )
                                                                    ),
                                                                )
                                                            ]
                                                        )
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="webinarpage",
            name="register_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="webinarpage",
            name="replay_link",
            field=models.URLField(blank=True),
        ),
    ]
