# Generated by Django 4.2.9 on 2024-03-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0008_alter_webinarpage_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WebinarIndexPage",
            new_name="WebinarsIndexPage",
        ),
        migrations.RenameModel(
            old_name="WebinarPage",
            new_name="WebinarsPage",
        ),
    ]
