# Generated by Django 4.2.9 on 2024-06-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_navigationsettings_alter_flatpage_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NavigationSettings",
            new_name="SocialMediaSettings",
        ),
    ]
