# Generated by Django 4.2.9 on 2024-06-11 10:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_rename_navigationsettings_socialmediasettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediasettings",
            name="contacts",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="additional_informations_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section_title_layout",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text_align",
                                    wagtail.blocks.CharBlock(
                                        help_text="center", required=False
                                    ),
                                ),
                                ("section_title", wagtail.blocks.CharBlock()),
                                (
                                    "section_subparagraph",
                                    wagtail.blocks.TextBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph_layout",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text_align",
                                    wagtail.blocks.CharBlock(
                                        help_text="center", required=False
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [("block", wagtail.blocks.RichTextBlock())]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "section",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "background_color",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "background_image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                ("title", wagtail.blocks.CharBlock()),
                                                (
                                                    "paragraph",
                                                    wagtail.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.blocks.URLBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "content_alignement",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="center",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "button_position",
                                    wagtail.blocks.CharBlock(
                                        help_text="center", required=False
                                    ),
                                ),
                                (
                                    "button_size",
                                    wagtail.blocks.CharBlock(
                                        help_text="btn__small, btn__xxsmall or btn__big"
                                    ),
                                ),
                                (
                                    "button_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="btn__primary, btn__secondary or outline__primary"
                                    ),
                                ),
                                ("button_url", wagtail.blocks.URLBlock()),
                                ("button_label", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    (
                        "content_box",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content_box",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "box_title",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                                (
                                                    "box_content",
                                                    wagtail.blocks.TextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "box_link",
                                                    wagtail.blocks.URLBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "icon_box",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon_box",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                ),
                                                ("title", wagtail.blocks.CharBlock()),
                                                (
                                                    "content",
                                                    wagtail.blocks.TextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.blocks.URLBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "map",
                        wagtail.blocks.StructBlock(
                            [("iframe", wagtail.blocks.TextBlock(required=False))]
                        ),
                    ),
                    (
                        "blank_space",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "height",
                                    wagtail.blocks.CharBlock(
                                        help_text="Enter empty space height (Note: CSS measurement units allowed)."
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="contacts_informations_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "contacts_informations",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "session_title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("paragraph", wagtail.blocks.TextBlock(required=False)),
                                (
                                    "contacts_card",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "content",
                                                wagtail.blocks.RichTextBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "social_media_card",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "content",
                                                wagtail.blocks.RichTextBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
