# Generated by Django 4.2.9 on 2024-03-20 18:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_teampage"),
    ]

    operations = [
        migrations.AddField(
            model_name="teampage",
            name="board_directors_section",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(required=False)),
                    ("sub_paragraph", wagtail.blocks.RichTextBlock(required=False)),
                    (
                        "board_director",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "image",
                                        wagtail.images.blocks.ImageChooserBlock(
                                            required=False
                                        ),
                                    ),
                                    ("name", wagtail.blocks.CharBlock(required=False)),
                                    (
                                        "function",
                                        wagtail.blocks.CharBlock(required=False),
                                    ),
                                    (
                                        "social_links",
                                        wagtail.blocks.ListBlock(
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "fa_class",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "profile_link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            )
                                        ),
                                    ),
                                ]
                            )
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="teampage",
            name="collaborators_section",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(required=False)),
                    ("sub_paragraph", wagtail.blocks.RichTextBlock(required=False)),
                    (
                        "collaborator",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("name", wagtail.blocks.CharBlock(required=False)),
                                    (
                                        "function",
                                        wagtail.blocks.CharBlock(required=False),
                                    ),
                                    (
                                        "social_links",
                                        wagtail.blocks.ListBlock(
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "fa_class",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "profile_link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            )
                                        ),
                                    ),
                                ]
                            )
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="teampage",
            name="overview_section",
            field=wagtail.fields.StreamField(
                [
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("heading", wagtail.blocks.CharBlock(required=False)),
                    ("paragraph", wagtail.blocks.RichTextBlock(required=False)),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
