# Generated by Django 4.2.9 on 2024-06-13 15:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0017_globalsettings_partnerssection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="main_partner_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="newsletter_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "newsletter_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "newsletter_widget_title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "newsletter_widget_subtitle",
                                    wagtail.blocks.TextBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="other_partners",
            field=wagtail.fields.StreamField(
                [
                    (
                        "partners_logo",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "logo",
                                        wagtail.images.blocks.ImageChooserBlock(
                                            required=False
                                        ),
                                    )
                                ]
                            )
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="section_subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="section_title",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="PartnersSection",
        ),
    ]
