# Generated by Django 4.2.9 on 2024-06-13 15:45

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_globalsettings_main_partner_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="section_subtitle",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="section_title",
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="section_subtitle_en",
            field=models.TextField(
                blank=True, help_text="Add content in english", null=True
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="section_subtitle_fr",
            field=models.TextField(
                blank=True, help_text="Add content in french", null=True
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="section_title_en",
            field=models.CharField(
                blank=True, help_text="Add content in english", null=True
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="section_title_fr",
            field=models.CharField(
                blank=True, help_text="Add content in french", null=True
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="newsletter_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "newsletter_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "newsletter_widget_title_en",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add content in english",
                                        required=False,
                                    ),
                                ),
                                (
                                    "newsletter_widget_title_fr",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add content in french",
                                        required=False,
                                    ),
                                ),
                                (
                                    "newsletter_widget_subtitle_en",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add content in english",
                                        required=False,
                                    ),
                                ),
                                (
                                    "newsletter_widget_subtitle_fr",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add content in french",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
