# Generated by Django 4.2.9 on 2024-06-13 17:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_remove_globalsettings_section_subtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="main_partner_logo",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="section_subtitle_en",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="section_subtitle_fr",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="section_title_en",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="section_title_fr",
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="main_partner",
            field=wagtail.fields.StreamField(
                [
                    (
                        "main_patner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "logo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "organisation_url",
                                    wagtail.blocks.URLBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="menus_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "menus_widget",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "widget_title_en",
                                        wagtail.blocks.CharBlock(
                                            help_text="Add content in english",
                                            required=False,
                                        ),
                                    ),
                                    (
                                        "widget_title_fr",
                                        wagtail.blocks.CharBlock(
                                            help_text="Add content in french",
                                            required=False,
                                        ),
                                    ),
                                    (
                                        "flat_menu",
                                        wagtail.blocks.ChoiceBlock(
                                            choices=[
                                                ("footer_menu_1", "Footermenu 1"),
                                                ("footer_menu_2", "Footermenu 2"),
                                                ("footer_menu_3", "Footermenu 3"),
                                            ],
                                            required=False,
                                        ),
                                    ),
                                ]
                            )
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="partners_section_heading",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "section_title_en",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add content in english",
                                        required=False,
                                    ),
                                ),
                                (
                                    "section_title_fr",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add content in french",
                                        required=False,
                                    ),
                                ),
                                (
                                    "section_subtitle_en",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add content in english",
                                        required=False,
                                    ),
                                ),
                                (
                                    "section_subtitle_fr",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add content in french",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="other_partners",
            field=wagtail.fields.StreamField(
                [
                    (
                        "other_partners",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "logo",
                                        wagtail.images.blocks.ImageChooserBlock(
                                            required=False
                                        ),
                                    ),
                                    (
                                        "organisation_url",
                                        wagtail.blocks.URLBlock(required=False),
                                    ),
                                ]
                            )
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
