# Generated by Django 4.2.9 on 2024-06-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_blogcategory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mooc",
            old_name="organisation",
            new_name="organization",
        ),
    ]
